### ISSUE TITLE
Empty peers / IP addresses after successful TorGuard setup

### ISSUE THREAD

**Issue by starkgate** [TorGuard/openwrt-scripts#8]
As the title says, I ran the TorGuard setup script successfully and rebooted the router. However, it looks like there's a lot missing from the config (see pictures below), meaning the WireGuard connection can't be established.

![firefox_4HBYJIdsDS](https://user-images.githubusercontent.com/12874678/104033478-dc3d0a00-51cf-11eb-8175-ebf5fe31a67c.png)
![firefox_GDE3Opwr8V](https://user-images.githubusercontent.com/12874678/104033483-dd6e3700-51cf-11eb-85e1-0a2319cf1142.png)

**Comment by starkgate** [comment]
After manually replacing the missing values with the ones from my TorGuard WireGuard config, the connection is established, but I don't have any access to the web. Not sure if this is a side effect of the problems during installation or something I should mention to TorGuard's support directly.

**Comment by TorGuard** [comment]
thanks for reporting, can you post result of (**_please edit private key, server ip etc... before posting online_**)?:
`uci show torguard`

**Comment by starkgate** [comment]
> thanks for reporting, can you post result of (**_please edit private key, server ip etc... before posting online_**)?:
> `uci show torguard`

Thank you very much for the quick fix. I've fixed it manually since, do you still need the log of uci?
